# Generated by Django 6.0.7 on 2026-07-31 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('media_coverage', 'Media Coverage'), ('press_release', 'Press Release')], max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('link', models.URLField(blank=True, help_text='Link to the full article (external site or PDF).')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-published_date'],
            },
        ),
    ]
