# Generated by Django 6.0.7 on 2026-08-04 10:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('closing_date', models.DateField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('cancelled', models.BooleanField(default=False, help_text='Tick to withdraw this posting, regardless of its closing date.')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
            },
        ),
    ]
