# Generated by Django 6.0.7 on 2026-08-05 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_procurement_group_admin_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderpage',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this tender notice was actually published/announced — can differ from the opening date.'),
        ),
    ]
