# Generated by Django 6.0.7 on 2026-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_tendernotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderpage',
            options={'ordering': ['-publish_date']},
        ),
    ]
