# Generated by Django 6.0.7 on 2026-08-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_alter_tenderpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderpage',
            name='summary',
            field=models.CharField(blank=True, help_text='One or two plain sentences shown under the tender title in the public tender list. If left blank, the start of the description below is used instead.', max_length=400),
        ),
    ]
