# Generated by Django 6.0.7 on 2026-08-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_tenderpage_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the tender page.')),
                ('collapsed_by_default', models.BooleanField(default=False, help_text='Start this group collapsed on the tender page. Useful for long lists such as annexures.')),
            ],
            options={
                'verbose_name': 'Document category',
                'verbose_name_plural': 'Document categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='tenderdocument',
            name='sub_tender_name',
            field=models.CharField(blank=True, help_text='Optional — if this document belongs to a specific sub-tender, enter its title exactly as entered above so it can be grouped correctly. Takes precedence over Category.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Groups this document under a collapsible heading on the tender page. Manage the list under Snippets - Document categories. Leave blank to list it under "Other Documents".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenders.documentcategory'),
        ),
    ]
