# Generated by Django 6.0.7 on 2026-08-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_seed_document_categories'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdocument',
            name='external_url',
            field=models.URLField(blank=True, help_text='Use instead of an upload to point at a file or folder hosted elsewhere (Google Drive, Dropbox, etc.). Opens in a new tab.', verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='tenderdocument',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Upload here for files hosted on this site. Leave blank if you are linking out with the field below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='tenderdocument',
            name='title',
            field=models.CharField(help_text='The label shown to visitors, e.g. "Annexure J - Equipment list" or "Drawings (Google Drive)".', max_length=255),
        ),
    ]
