# Generated by Django 6.0.7 on 2026-08-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_tenderdocument_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional one-line note shown under the group heading.', max_length=300)),
                ('collapsed_by_default', models.BooleanField(default=False, help_text='Start this panel collapsed on the tender list.')),
            ],
            options={
                'verbose_name': 'Tender group',
                'verbose_name_plural': 'Tender groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenderpage',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional. Tenders sharing a group are shown together in one collapsible panel on the tender list. Manage groups under Snippets - Tender groups. Leave blank to list this tender on its own.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.tendergroup'),
        ),
    ]
