# Generated by Django 6.0.7 on 2026-07-31 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSocialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('environment', 'Environment'), ('social', 'Social')], max_length=20)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Environment & Social Document',
                'verbose_name_plural': 'Environment & Social Documents',
                'ordering': ['category', 'title'],
            },
        ),
    ]
