# Generated by Django 6.0.7 on 2026-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('dam_site', 'Dam Site'), ('powerhouse', 'Powerhouse'), ('main_office', 'Main Office'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Map Location',
                'verbose_name_plural': 'Project Map Locations',
                'ordering': ['order', 'name'],
            },
        ),
    ]
