# Generated by Django 6.0.7 on 2026-08-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmap', '0002_seed_known_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlocation',
            name='latitude',
            field=models.FloatField(help_text='Decimal degrees only, e.g. 27.7287 — not the whole "27.7287, 91.1364" pair from Google Maps.'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='longitude',
            field=models.FloatField(help_text='Decimal degrees only, e.g. 91.1364 — no ° symbol or N/E/S/W letters.'),
        ),
    ]
