# Generated by Django 6.0.7 on 2026-08-04 05:02

import django.core.validators
import django.db.models.deletion
import grievance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grievance Category',
                'verbose_name_plural': 'Grievance Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('cid_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('village_gewog', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=grievance.models.grievance_audio_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a', 'ogg', 'webm'])])),
                ('video_file', models.FileField(blank=True, null=True, upload_to=grievance.models.grievance_video_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])])),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='grievance.grievancecategory')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
