# Generated by Django 6.0.7 on 2026-08-04 10:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLDPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('date', models.DateField(help_text='Used for ordering and for choosing the 4 shown on the homepage.')),
                ('description', models.TextField(blank=True)),
                ('target_participants', models.PositiveIntegerField(default=0)),
                ('actual_participants', models.PositiveIntegerField(default=0)),
                ('male_participants', models.PositiveIntegerField(default=0)),
                ('female_participants', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CLDP Activity',
                'verbose_name_plural': 'CLDP Activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CLDPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(blank=True, help_text='Intro paragraph shown at the top of the CLD Dashboard, on the homepage and on /cldp/.')),
            ],
            options={
                'verbose_name': 'CLD Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='CLDPActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cldp.cldpactivity')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
