# Generated by Django 6.0.7 on 2026-09-08 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cldp', '0002_seed_first_activity'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLDPAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Optional. E.g. a registration form or bot link.', max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Used for ordering.')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_on', models.DateField(blank=True, help_text='Optional — hides this from the homepage after this date; stays archived on the CLD Dashboard.', null=True)),
                ('document', models.ForeignKey(blank=True, help_text='Optional file to attach (e.g. a flyer or registration form).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'CLDP Announcement',
                'ordering': ['-date'],
            },
        ),
    ]
