# Generated by Django 6.0.7 on 2026-09-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cldp', '0003_cldpannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cldpannouncement',
            name='document_label',
            field=models.CharField(blank=True, help_text='Button text for the document, e.g. "Registration Form (PDF)". Defaults to the document\'s own title if left blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='cldpannouncement',
            name='link_label',
            field=models.CharField(blank=True, help_text='Button text for the link, e.g. "Register" or "Join the WhatsApp Group". Defaults to "Register / Learn More" if left blank.', max_length=255),
        ),
    ]
