# Generated by Django 6.0.7 on 2026-08-21 06:41

from django.db import migrations, models


MILESTONES = [
    dict(year_label="2004", sort_date="2004-01-01", status="completed",
         title="Project Identified in PSMP", description="Installed capacity as 400 MW plant."),
    dict(year_label="2011", sort_date="2011-01-01", status="completed",
         title="PFS by Norplan of Norway", description="Installed capacity assessed at 1,230 MW."),
    dict(year_label="2015", sort_date="2015-01-01", status="completed",
         title="DPR by DGPC with EIPL", description="Installed capacity optimized at 1,125 MW."),
    dict(year_label="2019", sort_date="2019-01-01", status="completed",
         title="PSMP-2040 by JICA", description="Earmarked for development by 2026–2030 (1,125 MW)."),
    dict(year_label="2022 – 2025", sort_date="2022-01-01", status="completed",
         title="DPR Update with Support from World Bank",
         description="Planning, design and detailed engineering including ESIA."),
    dict(year_label="2025", sort_date="2025-01-01", status="completed",
         title="SPV Formation and Commercial Agreements", description="DHPL incorporated between DGPC & TPC."),
]

ACHIEVEMENTS = [
    dict(title="Safety Training", date="2026-07-01",
         description="764 hours of employee safety training conducted to strengthen awareness and competency."),
    dict(title="Accident Free Days", date="2026-07-01",
         description="550 accident-free days through continuous safety commitment."),
    dict(title="1.3 Million Safe Man-Hours", date="2026-07-01",
         description="1.3 million safe man-hours achieved without a lost-time injury."),
    dict(title="CLDP", date="2026-07-01",
         description="Successfully launched the CLDP program with 22 participants in the refresher course for household electrical wiring."),
]


def seed_initial_data(apps, schema_editor):
    Milestone = apps.get_model("home", "Milestone")
    Achievement = apps.get_model("home", "Achievement")
    for entry in MILESTONES:
        Milestone.objects.create(**entry)
    for entry in ACHIEVEMENTS:
        Achievement.objects.create(**entry)


def remove_seeded_data(apps, schema_editor):
    Milestone = apps.get_model("home", "Milestone")
    Achievement = apps.get_model("home", "Achievement")
    Milestone.objects.filter(title__in=[m["title"] for m in MILESTONES]).delete()
    Achievement.objects.filter(title__in=[a["title"] for a in ACHIEVEMENTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(help_text='Used for ordering, and displayed as e.g. "Jul 2026".')),
            ],
            options={
                'verbose_name': 'Key Achievement',
                'verbose_name_plural': 'Key Achievements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='Displayed year or range, e.g. "2004" or "2022 – 2025".', max_length=50)),
                ('sort_date', models.DateField(help_text='Used only to order milestones chronologically — pick the start of the period shown above.')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('upcoming', 'Upcoming')], default='completed', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Key Milestone',
                'verbose_name_plural': 'Key Milestones',
                'ordering': ['sort_date'],
            },
        ),
        migrations.RunPython(seed_initial_data, remove_seeded_data),
    ]
