# Generated by Django 6.0.7 on 2026-08-21 09:12

import wagtail.fields
from django.db import migrations


def blank_out_body(apps, schema_editor):
    # The existing body is "" (empty string, from the old RichTextField)
    # — not valid JSON. SQLite rebuilds the whole table for this type
    # change and re-validates every row against the new JSON_VALID
    # constraint, so this needs to become a valid empty array first,
    # while the column is still plain text.
    ProjectPage = apps.get_model("home.ProjectPage")
    ProjectPage.objects.filter(body="").update(body="[]")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_create_projectpage'),
    ]

    operations = [
        migrations.RunPython(blank_out_body, noop),
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.fields.StreamField([('stat_cards', 4), ('text_section', 7), ('spec_table', 11), ('bullet_list', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "1,125 MW"', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Installed Capacity"', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('cards', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 7: ('wagtail.blocks.StructBlock', [[('heading', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 9: ('wagtail.blocks.StructBlock', [[('label', 8), ('value', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 5), ('rows', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 500}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 12), ('items', 14)]], {})}),
        ),
    ]
