# Generated by Django 6.0.7 on 2026-08-21 10:31

import django.db.models.deletion
from django.db import migrations, models

BOARD_MEMBERS = [
    ("Dasho Karma Tshering", "Chairman"),
    ("Dasho Leki Wangmo", "Board Member"),
    ("Dasho Chhewang Rinzin", "Board Member"),
    ("Dr. Praveer Sinha", "Board Member"),
    ("Ms. Anjali Pandey", "Board Member"),
    ("Dasho Lungten Jamtsho", "Board Member"),
    ("Mr. Kumar Pritam Kumar", "Board Member"),
]


def seed_board_members(apps, schema_editor):
    BoardMember = apps.get_model("structure.BoardMember")
    for order, (name, designation) in enumerate(BOARD_MEMBERS):
        BoardMember.objects.create(name=name, designation=designation, order=order)


def remove_board_members(apps, schema_editor):
    BoardMember = apps.get_model("structure.BoardMember")
    BoardMember.objects.filter(name__in=[n for n, _ in BOARD_MEMBERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(seed_board_members, remove_board_members),
    ]
